# Generated by Django 5.2.14 on 2026-06-01 18:15

import django.db.models.deletion
import django_geoaddress.fields
import namedid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAtlasProviderModel',
            fields=[
                ('name', models.CharField(help_text='Provider name (e.g., insee)', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, default='', help_text='Provider display name', max_length=255, verbose_name='Display Name')),
                ('description', models.CharField(blank=True, default='', help_text='Provider description', max_length=255, verbose_name='Description')),
                ('priority', models.IntegerField(help_text='Provider priority', verbose_name='Priority')),
                ('config_status_str', models.CharField(blank=True, default='', help_text='Config status', max_length=255, verbose_name='Config status')),
                ('config_prefix', models.CharField(blank=True, default='', help_text='Config prefix', max_length=255, verbose_name='Config prefix')),
                ('config_keys', models.JSONField(help_text='Config keys', verbose_name='Config keys')),
                ('missing_config_keys', models.JSONField(help_text='Missing config keys', verbose_name='Missing config keys')),
                ('is_config_ready', models.BooleanField(help_text='Is config ready', verbose_name='Is config ready')),
                ('package_status_str', models.CharField(blank=True, default='', help_text='Package status', max_length=255, verbose_name='Package status')),
                ('required_packages', models.JSONField(help_text='Required packages', verbose_name='Required packages')),
                ('missing_packages', models.JSONField(help_text='Missing packages', verbose_name='Missing packages')),
                ('are_packages_installed', models.BooleanField(help_text='Are packages installed', verbose_name='Are packages installed')),
                ('service_status_str', models.CharField(blank=True, default='', help_text='Service status', max_length=255, verbose_name='Service status')),
                ('missing_services', models.JSONField(help_text='Missing services', verbose_name='Missing services')),
                ('services', models.JSONField(help_text='Services', verbose_name='Services')),
                ('are_services_implemented', models.BooleanField(help_text='Are services implemented', verbose_name='Are services implemented')),
                ('geo_data', models.CharField(blank=True, default='', help_text='Data source', max_length=255, verbose_name='Data source')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['-priority', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasVirtualDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Virtual Document',
                'verbose_name_plural': 'Virtual Documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasVirtualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Virtual Event',
                'verbose_name_plural': 'Virtual Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasVirtualOrganization',
            fields=[
                ('organizationatlas_id', models.CharField(help_text='Organizationatlas ID', max_length=500, primary_key=True, serialize=False, verbose_name='Organizationatlas ID')),
                ('denomination', models.CharField(blank=True, default='', help_text='Denomination', max_length=255, verbose_name='Denomination')),
                ('reference', models.CharField(blank=True, default='', help_text='Reference', max_length=255, verbose_name='Reference')),
                ('source_field', models.CharField(blank=True, default='', help_text='Source field', max_length=255, verbose_name='Source field')),
                ('country_code', models.CharField(blank=True, default='', help_text='Country code', max_length=255, verbose_name='Country code')),
                ('address', models.CharField(blank=True, default='', help_text='Address', max_length=255, verbose_name='Address')),
                ('address_json', models.JSONField(help_text='Address JSON', verbose_name='Address JSON')),
                ('data_source', models.CharField(blank=True, default='', help_text='Data source', max_length=255, verbose_name='Data source')),
                ('backend', models.CharField(blank=True, default='', help_text='Backend display name', max_length=255, verbose_name='Backend display name')),
                ('backend_name', models.CharField(blank=True, default='', help_text='Simple backend name (e.g., insee)', max_length=255, verbose_name='Simple backend name (e.g., insee)')),
            ],
            options={
                'verbose_name': 'Virtual Organization',
                'verbose_name_plural': 'Virtual Organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('denomination', models.CharField(help_text='Organization denomination', max_length=255, verbose_name='Denomination')),
                ('code', models.CharField(help_text='Organization code', max_length=255, verbose_name='Code')),
                ('named_id', namedid.fields.NamedIDField(blank=False, help_text='Named ID', max_length=512, null=False, source_fields=['denomination', 'code'], unique=True, verbose_name='Named ID')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.CharField(help_text='Referentiel name', max_length=255, verbose_name='Name')),
                ('code', models.CharField(help_text='Referentiel code', max_length=255, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', help_text='Referentiel description', verbose_name='Description')),
                ('characteristics', models.TextField(blank=True, default='', help_text='Referentiel characteristics', verbose_name='Characteristics')),
                ('priority', models.IntegerField(default=0, help_text='Referentiel priority', verbose_name='Priority')),
                ('usage_type', models.CharField(choices=[('description', 'Description'), ('configuration', 'Configuration'), ('characteristics', 'Characteristics')], default='description', help_text='Usage type', max_length=100, verbose_name='Usage Type')),
            ],
            options={
                'verbose_name': 'Referentiel',
                'verbose_name_plural': 'Referentiels',
                'ordering': ['-priority', 'category', 'code'],
                'indexes': [models.Index(fields=['category'], name='django_orga_categor_78be17_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('officer_or_owner', models.CharField(choices=[('officer', 'Officer'), ('owner', 'Ultimate Beneficial Owner')], help_text='Type of person (officer, owner)', max_length=100, verbose_name='Person Type')),
                ('first_name', models.CharField(blank=True, default='', help_text='First name of the person', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', help_text='Last name of the person', max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, help_text='Birth date of the person', null=True, verbose_name='Birth Date')),
                ('organization', models.ForeignKey(help_text='Organization this person belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='to_organizationatlasperson', to='django_organizationatlas.organizationatlasorganization', verbose_name='Organization')),
                ('gender', models.ForeignKey(blank=True, help_text='Gender or holding status of the person', limit_choices_to=models.Q(('category__in', ('gender', 'gender_response', 'gender_structure'))), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='django_organizationatlas.organizationatlasreferentiel', verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Organization Person',
                'verbose_name_plural': 'Organization Persons',
                'ordering': ['officer_or_owner', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasOrganizationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('valid_from', models.DateField(blank=True, help_text='Date from which the information is valid (depuis)', null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, help_text="Date until which the information was valid (jusqu'au, empty = still current)", null=True, verbose_name='Valid to')),
                ('other', models.CharField(blank=True, default='', help_text="Free description when relation type is 'Other'", max_length=255, verbose_name='Other')),
                ('from_organization', models.ForeignKey(help_text='Organization that holds this relation', on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='django_organizationatlas.organizationatlasorganization', verbose_name='From Organization')),
                ('to_organization', models.ForeignKey(help_text='Organization targeted by this relation', on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='django_organizationatlas.organizationatlasorganization', verbose_name='To Organization')),
                ('relation_type', models.ForeignKey(blank=True, help_text='Type of relationship between the two organizations', limit_choices_to={'category': 'organization_relation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_relations', to='django_organizationatlas.organizationatlasreferentiel', verbose_name='Relation Type')),
            ],
            options={
                'verbose_name': 'Organization Relation',
                'verbose_name_plural': 'Organization Relations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organizationatlasorganization',
            name='organization_type',
            field=models.ForeignKey(blank=True, help_text='Functional classification of the legal entity', limit_choices_to={'category': 'organization_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='django_organizationatlas.organizationatlasreferentiel', verbose_name='Organization Type'),
        ),
        migrations.CreateModel(
            name='OrganizationAtlasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('valid_from', models.DateField(blank=True, help_text='Date from which the information is valid (depuis)', null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, help_text="Date until which the information was valid (jusqu'au, empty = still current)", null=True, verbose_name='Valid to')),
                ('data_type', models.CharField(help_text='Type of data (e.g., denomination, siren, capital, employees)', max_length=100, verbose_name='Data Type')),
                ('value_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('json', 'JSON')], default='str', help_text='Type of the value (str, int, float, json)', max_length=10, verbose_name='Value Type')),
                ('value', models.TextField(help_text='Data value', verbose_name='Value')),
                ('organization', models.ForeignKey(help_text='Organization this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='to_organizationatlasdata', to='django_organizationatlas.organizationatlasorganization', verbose_name='Organization')),
                ('referentiel', models.ManyToManyField(blank=True, help_text='Referentiel this data belongs to', related_name='to_organizationatlasdata', to='django_organizationatlas.organizationatlasreferentiel', verbose_name='Referentiel')),
            ],
            options={
                'verbose_name': 'Organization Data',
                'verbose_name_plural': 'Organization Data',
                'ordering': ['data_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasStakeholderRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('valid_from', models.DateField(blank=True, help_text='Date from which the information is valid (depuis)', null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, help_text="Date until which the information was valid (jusqu'au, empty = still current)", null=True, verbose_name='Valid to')),
                ('other', models.CharField(blank=True, default='', help_text="Free description when relation type is 'Other'", max_length=255, verbose_name='Other')),
                ('from_organization', models.ForeignKey(blank=True, help_text='Organization stakeholder (mutually exclusive with From Person)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_relations_as_holder', to='django_organizationatlas.organizationatlasorganization', verbose_name='From Organization')),
                ('from_person', models.ForeignKey(blank=True, help_text='Physical person stakeholder (mutually exclusive with From Organization)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_relations', to='django_organizationatlas.organizationatlasperson', verbose_name='From Person')),
                ('relation_type', models.ForeignKey(blank=True, help_text='Nature of the stakeholder relationship', limit_choices_to={'category': 'stakeholder_relation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_relations', to='django_organizationatlas.organizationatlasreferentiel', verbose_name='Relation Type')),
                ('to_organization', models.ForeignKey(help_text='Organization targeted by this stakeholder relation', on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_relations', to='django_organizationatlas.organizationatlasorganization', verbose_name='To Organization')),
            ],
            options={
                'verbose_name': 'Stakeholder Relation',
                'verbose_name_plural': 'Stakeholder Relations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event_type', models.CharField(help_text='Type of event (e.g., status_change, modification, capital_change)', max_length=100, verbose_name='Event Type')),
                ('title', models.CharField(help_text='Event title', max_length=255, verbose_name='Title')),
                ('date', models.DateField(blank=True, help_text='Event date', null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, help_text='Event description', verbose_name='Description')),
                ('organization', models.ForeignKey(help_text='Organization this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='django_organizationatlas.organizationatlasorganization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Event',
                'verbose_name_plural': 'Organization Events',
                'indexes': [models.Index(fields=['organization', 'country_code'], name='django_orga_organiz_55420b_idx'), models.Index(fields=['event_type'], name='django_orga_event_t_78f699_idx'), models.Index(fields=['date'], name='django_orga_date_cc9745_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('document_type', models.CharField(help_text='Type of document (e.g., bodacc, kbis, balo)', max_length=100, verbose_name='Document Type')),
                ('title', models.CharField(help_text='Document title', max_length=255, verbose_name='Title')),
                ('date', models.DateField(blank=True, help_text='Document date', null=True, verbose_name='Date')),
                ('url', models.URLField(blank=True, help_text='URL to access the document', verbose_name='URL')),
                ('content', models.TextField(blank=True, help_text='Document content or summary', verbose_name='Content')),
                ('organization', models.ForeignKey(help_text='Organization this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='django_organizationatlas.organizationatlasorganization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Document',
                'verbose_name_plural': 'Organization Documents',
                'indexes': [models.Index(fields=['organization', 'country_code'], name='django_orga_organiz_e544d7_idx'), models.Index(fields=['document_type'], name='django_orga_documen_9e8683_idx'), models.Index(fields=['date'], name='django_orga_date_1c6a36_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAtlasAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('valid_from', models.DateField(blank=True, help_text='Date from which the information is valid (depuis)', null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, help_text="Date until which the information was valid (jusqu'au, empty = still current)", null=True, verbose_name='Valid to')),
                ('address', django_geoaddress.fields.GeoaddressField(help_text='Organization address', verbose_name='Address')),
                ('is_headquarters', models.BooleanField(default=False, help_text="Whether this address is the organization's headquarters", verbose_name='Is headquarters')),
                ('organization', models.ForeignKey(help_text='Organization this address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='to_organizationatlasaddress', to='django_organizationatlas.organizationatlasorganization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Address',
                'verbose_name_plural': 'Organization Addresses',
                'ordering': ['-is_headquarters', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'address'], name='django_orga_organiz_20c016_idx'), models.Index(fields=['organization', 'is_headquarters'], name='django_orga_organiz_3b7225_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationatlasperson',
            index=models.Index(fields=['organization', 'officer_or_owner'], name='django_orga_organiz_4d2f31_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationatlasorganizationrelation',
            index=models.Index(fields=['from_organization', 'to_organization'], name='django_orga_from_or_157656_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationatlasorganizationrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('from_organization', 'to_organization', 'relation_type'), name='unique_open_organization_relation'),
        ),
        migrations.AddIndex(
            model_name='organizationatlasorganization',
            index=models.Index(fields=['-created_at'], name='django_orga_created_6ca8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationatlasdata',
            index=models.Index(fields=['organization', 'country_code'], name='django_orga_organiz_0744e2_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationatlasdata',
            index=models.Index(fields=['data_type'], name='django_orga_data_ty_7ff4e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationatlasdata',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('organization', 'source', 'country_code', 'data_type'), name='unique_open_organizationatlasdata', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='organizationatlasstakeholderrelation',
            index=models.Index(fields=['to_organization'], name='django_orga_to_orga_fb010a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationatlasstakeholderrelation',
            index=models.Index(fields=['from_person', 'to_organization'], name='django_orga_from_pe_394a72_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationatlasstakeholderrelation',
            index=models.Index(fields=['from_organization', 'to_organization'], name='django_orga_from_or_5a653b_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationatlasstakeholderrelation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('from_organization__isnull', True), ('from_person__isnull', False)), models.Q(('from_organization__isnull', False), ('from_person__isnull', True)), _connector='OR'), name='stakeholder_relation_exactly_one_from'),
        ),
        migrations.AddConstraint(
            model_name='organizationatlasstakeholderrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('from_person', 'from_organization', 'to_organization', 'relation_type'), name='unique_open_stakeholder_relation'),
        ),
    ]
