# Generated by Django 5.2.15 on 2026-06-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_organizationatlas', '0003_referentiel_country_code_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAtlasDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('valid_from', models.DateField(blank=True, help_text='Date from which the information is valid (depuis)', null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, help_text="Date until which the information was valid (jusqu'au, empty = still current)", null=True, verbose_name='Valid to')),
                ('delegation', models.ForeignKey(help_text='Organization that receives the delegation', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='django_organizationatlas.organizationatlasorganization', verbose_name='To Organization')),
                ('organization', models.ForeignKey(help_text='Organization that grants the delegation', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='django_organizationatlas.organizationatlasorganization', verbose_name='From Organization')),
            ],
            options={
                'verbose_name': 'Delegation',
                'verbose_name_plural': 'Delegations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'delegation'], name='django_orga_organiz_ad235b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('organization', 'delegation'), name='unique_open_organization_delegation')],
            },
        ),
    ]
